// Interns.Core/Models/ApplicationUser.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace Interns.Core.Models
{
    public class ApplicationUser
    {
        [Key]
        public Guid Id { get; set; }


        [Required]
        public string EmployeeId { get; set; } // username given by Admin


        public string FullName { get; set; }
        public string Email { get; set; }


        [Required]
        public Role Role { get; set; }


        // Link to trainer/manager if this user is an intern
        public Guid? TrainerId { get; set; }
        public Guid? ManagerId { get; set; }


        // Password is stored as a hash generated by Admin
        [Required]
        public string PasswordHash { get; set; }


        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}





